### PR TITLE
Use MiniCssExtractPlugin in dev and prod

### PR DESCRIPTION
**Pull request by simonbru**
MiniCssExtractPlugin supports hot module reloading since v0.6.0.

See https://github.com/liip/styleguide-starterkit/commit/75d0fffdd5cf940c4ff0880526034083cf5c1601

**Blocker**: This won't work out of the box until drifter's package.json template gets updated.
https://github.com/liip/drifter/blob/master/provisioning/roles/nodejs/templates/package.json.webpack.j2#L19

Drifter PR: https://github.com/liip/drifter/pull/271

### CODE REVIEW

**Review by LeBenLeBen — CHANGES_REQUESTED** [review]
It misses changes in the [template](https://github.com/liip/django-template/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/templates/base.html), you must remove mentions of `webpack_dev_server`, the CSS file must be always included whatever the environment.

**Review by LeBenLeBen — APPROVED** [review]

**Comment by LeBenLeBen** [comment]
@simonbru Drifter MR got merged, I guess you can update it so we can merge this one as well.

**Comment by simonbru** [comment]
@LeBenLeBen We must wait for a Drifter release first since Drifter's install script checks out the latest release (git tag) and not master.

**Comment by LeBenLeBen** [comment]
Maybe @sephii can make a release for us? 😏

**Comment by sephii** [comment]
Done!

**Comment by simonbru** [comment]
Great! I created a project from scratch and it now gets the right version for `mini-css-extract-plugin` in package.json (and HMR works)

**Pull request merged**
